# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-24 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayName', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('numDeliveries', models.IntegerField()),
                ('helper', models.CharField(max_length=500)),
                ('driver', models.CharField(max_length=500)),
                ('storeNum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=500)),
                ('lastName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='weekNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Week'),
        ),
    ]
