# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-25 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='weekNum',
        ),
        migrations.AddField(
            model_name='day',
            name='saturday',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
