# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-27 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170527_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
