# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-28 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='truck',
            field=models.CharField(max_length=500, null='true'),
        ),
    ]
