# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-28 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170528_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='truck',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='main.Truck'),
        ),
    ]
