# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170528_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='isOff',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='day',
            name='storeNum2',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='day',
            name='truck2',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
