# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170701_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='dayName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='driver',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='helper',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='isOff',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='numDeliveries',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='saturday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='storeNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='truck',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='truck2',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
