# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170702_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='truck2',
        ),
    ]
