# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_day_truck2'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='overtimeNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='truck',
            field=models.CharField(max_length=500),
        ),
    ]
