# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20170704_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='storeNum2',
            field=models.IntegerField(null=True),
        ),
    ]
